In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [26]:
fuel_consumption_raw = pd.read_csv('data/fuel_comsumption.csv')
passengers_raw = pd.read_csv('data/passengers_2019_01.csv')
flights_raw = pd.read_csv('data/flights_2019_01.csv')

In [27]:
flights_perc_missing = flights_raw.isnull().sum() * 100 / len(flights_raw)
passengers_perc_missing = passengers_raw.isnull().sum() * 100 / len(passengers_raw)
fuel_perc_missing = fuel_consumption_raw.isnull().sum() * 100 / len(fuel_consumption_raw)
print("flights percentage of missing per column:",flights_perc_missing,'\n')
print("passengers percentage of missing per column:",passengers_perc_missing,'\n')
print("fuel percentage of missing per column:",fuel_perc_missing,'\n')

flights percentage of missing per column: fl_date                  0.000000
mkt_unique_carrier       0.000000
branded_code_share       0.000000
mkt_carrier              0.000000
mkt_carrier_fl_num       0.000000
op_unique_carrier        0.000000
tail_num                 0.733580
op_carrier_fl_num        0.000000
origin_airport_id        0.000000
origin                   0.000000
origin_city_name         0.000000
dest_airport_id          0.000000
dest                     0.000000
dest_city_name           0.000000
crs_dep_time             0.000000
dep_time                 2.990532
dep_delay                2.991001
taxi_out                 3.037036
wheels_off               3.037036
wheels_on                3.122059
taxi_in                  3.122059
crs_arr_time             0.000000
arr_time                 3.122059
arr_delay                3.288191
cancelled                0.000000
cancellation_code       96.938851
diverted                 0.000000
dup                      0.000000
crs_elapsed_time         0.001253
actual_elapsed_time      3.288191
air_time                 3.288191
flights                  0.000000
distance                 0.000000
carrier_delay           81.657530
weather_delay           81.657530
nas_delay               81.657530
security_delay          81.657530
late_aircraft_delay     81.657530
first_dep_time          99.313708
total_add_gtime         99.313864
longest_add_gtime       99.313708
no_name                100.000000
dtype: float64

passengers percentage of missing per column: departures_scheduled     0.0
departures_performed     0.0
payload                  0.0
seats                    0.0
passengers               0.0
freight                  0.0
mail                     0.0
distance                 0.0
ramp_to_ramp             0.0
air_time                 0.0
unique_carrier           0.0
airline_id               0.0
unique_carrier_name      0.0
region                   0.0
carrier                  0.0
carrier_name             0.0
carrier_group            0.0
carrier_group_new        0.0
origin_airport_id        0.0
origin_city_market_id    0.0
origin                   0.0
origin_city_name         0.0
origin_country           0.0
origin_country_name      0.0
dest_airport_id          0.0
dest_city_market_id      0.0
dest                     0.0
dest_city_name           0.0
dest_country             0.0
dest_country_name        0.0
aircraft_group           0.0
aircraft_type            0.0
aircraft_config          0.0
year                     0.0
month                    0.0
distance_group           0.0
class                    0.0
data_source              0.0
dtype: float64

fuel percentage of missing per column: month                0.000000
airline_id           0.032949
unique_carrier       0.032949
carrier              0.000000
carrier_name         0.032949
carrier_group_new    0.000000
sdomt_gallons        0.032949
satl_gallons         0.032949
spac_gallons         0.032949
slat_gallons         0.065898
sint_gallons         0.032949
ts_gallons           0.032949
tdomt_gallons        0.098847
tint_gallons         0.032949
total_gallons        0.197694
sdomt_cost           0.000000
satl_cost            0.032949
spac_cost            0.032949
slat_cost            0.032949
sint_cost            0.032949
ts_cost              0.000000
tdomt_cost           0.000000
tint_cost            0.032949
total_cost           0.000000
year                 0.000000
dtype: float64

In [28]:
#Dropping columns with above 75 percentage of missing values in flights_raw
#Dropping tail_num column;
flights_raw = flights_raw.drop(columns = ['no_name', 'longest_add_gtime','total_add_gtime'
                                          ,'first_dep_time','late_aircraft_delay','security_delay',
                                          'nas_delay','weather_delay','carrier_delay','cancellation_code','tail_num'],axis=1)

In [92]:
#Dropping rows on fuel_consumption with missing values
#There is total of 25 missing rows out of 3035
fuel_consumption_raw = fuel_consumption_raw.dropna()

In [75]:
#Filling the Nan in the flights_raw data
flights_raw['dep_time'] = flights_raw['dep_time'].fillna(flights_raw['dep_time'].mean())
flights_raw['dep_delay'] = flights_raw['dep_delay'].fillna(flights_raw['dep_delay'].mean())
flights_raw['taxi_out'] = flights_raw['taxi_out'].fillna(flights_raw['taxi_out'].mean())
flights_raw['wheels_off'] = flights_raw['wheels_off'].fillna(flights_raw['wheels_off'].mean())
flights_raw['wheels_on'] = flights_raw['wheels_on'].fillna(flights_raw['wheels_off'].mean())
flights_raw['taxi_in'] = flights_raw['taxi_in'].fillna(flights_raw['taxi_in'].mean())
flights_raw['arr_time'] = flights_raw['arr_time'].fillna(flights_raw['arr_time'].mean())
flights_raw['arr_delay'] = flights_raw['arr_delay'].fillna(flights_raw['arr_delay'].mean())
flights_raw['actual_elapsed_time'] = flights_raw['actual_elapsed_time'].fillna(flights_raw['actual_elapsed_time'].mean())
flights_raw['crs_elapsed_time'] = flights_raw['crs_elapsed_time'].fillna(flights_raw['crs_elapsed_time'].mean())
flights_raw['air_time'] = flights_raw['air_time'].fillna(flights_raw['air_time'].mean())

In [101]:
#exporting cleaned files to csv
flights_raw.to_csv('flights_2019_cleaned.csv')
passengers_raw.to_csv('passengers_2019_cleaned.csv')
fuel_consumption_raw.to_csv('fuel_consumption_2019_cleaned.csv')

In [115]:
flights_raw.loc[flights_raw['arr_delay'] == 0]

,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier,mkt_carrier_fl_num,op_unique_carrier,op_carrier_fl_num,origin_airport_id,origin,origin_city_name,...,arr_time,arr_delay,cancelled,diverted,dup,crs_elapsed_time,actual_elapsed_time,air_time,flights,distance
3,2019-01-01,AA,AA_CODESHARE,AA,5621,OH,5621,11057,CLT,"Charlotte, NC",...,1328.0,0.0,0,0,N,108.0,109.0,76.0,1,490
9,2019-01-01,AA,AA_CODESHARE,AA,5626,OH,5626,11057,CLT,"Charlotte, NC",...,1909.0,0.0,0,0,N,56.0,46.0,19.0,1,75
14,2019-01-01,AA,AA_CODESHARE,AA,5632,OH,5632,13296,MHT,"Manchester, NH",...,1513.0,0.0,0,0,N,154.0,155.0,141.0,1,737
119,2019-01-01,AA,AA_CODESHARE,AA,5271,OH,5271,14100,PHL,"Philadelphia, PA",...,1749.0,0.0,0,0,N,124.0,125.0,92.0,1,554
151,2019-01-01,AA,AA_CODESHARE,AA,5229,OH,5229,11057,CLT,"Charlotte, NC",...,1220.0,0.0,0,0,N,120.0,122.0,93.0,1,511
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
638368,2019-01-31,AA,AA_CODESHARE,AA,4480,YX,4480,11066,CMH,"Columbus, OH",...,2200.0,0.0,0,0,N,106.0,100.0,73.0,1,479
638383,2019-01-31,AA,AA_CODESHARE,AA,4695,YX,4695,13198,MCI,"Kansas City, MO",...,919.0,0.0,0,0,N,192.0,182.0,158.0,1,1251
638405,2019-01-31,AA,AA,AA,683,AA,683,14492,RDU,"Raleigh/Durham, NC",...,821.0,0.0,0,0,N,72.0,79.0,45.0,1,130
638459,2019-01-31,AA,AA,AA,757,AA,757,11057,CLT,"Charlotte, NC",...,1620.0,0.0,0,0,N,115.0,108.0,92.0,1,600
638507,2019-01-31,AA,AA,AA,801,AA,801,11298,DFW,"Dallas/Fort Worth, TX",...,2306.0,0.0,0,0,N,81.0,86.0,68.0,1,431